# Use an official Python runtime as a parent image
FROM python:3.6

# Install R base
RUN apt-get update && apt-get install -y r-base

# Install rpy2
RUN pip install rpy2

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run test.py when the container launches
CMD ["python", "test.py"]
